constants: check if the 'tmp' dir exists, not only XDG_CACHE_HOME
If the path `$XDG_CACHE_HOME/tmp` doesn't exist but `$XDG_DATA_HOME`
does, the TEMP_DIR would be set to the home path. This would later
cause the following exception in `_download_awacy_gamelist_thread`
as a result

```
Exception in thread Thread-5 (_download_awacy_gamelist_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/loathingkernel/Projects/external/ProtonUp-Qt/pupgui2/util.py", line 457, in _download_awacy_gamelist_thread
    with open(LOCAL_AWACY_GAME_LIST, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/loathingkernel/.cache/tmp/pupgui2.a70200/awacy_games.json'
```